services:
  jikanflow:
    build:
      context: ./jikanflow
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/jikanflow
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=119201
    # env_file:
    #   - jikanflow/src/main/resources/application.properties
    networks:
      - backend

  jikanflow-user:
    build:
      context: ./jikanflow-user
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"      # RabbitMQ
      - "15672:15672"    # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - backend

networks:
  backend:
    driver: bridge