services:
  jikanflow:
    build:
      context: ./jikanflow
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/jikanflow
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=119201
    # env_file:
    #   - jikanflow/src/main/resources/application.properties
    networks:
      - backend

  jikanflow-notifications:
    build:
      context: ./jikanflow-notifications
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"      # RabbitMQ
      - "15672:15672"    # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: jikanflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 119201
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend


networks:
  backend:
    driver: bridge
volumes:
  pgdata: