spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jikanflow
    username: postgres
    password: 119201
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 4000

jwt:
  secret: YjBhZDdiZGJhOTE0MDg1NWViNDcyMzEyOTJkM2I4NzFjOTdiNDc2ZDE3OTc2MjZkZDgyYWIwZWMyOTlmZGNiMQ==

management:
  endpoints:
    web:
      exposure:
        exclude: "*"
