spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/jikanflow-user
      database: jikanflow-user

management:
  endpoints:
    web:
      exposure:
        exclude: "*"

server:
  port: 4001